In [37]:
import numpy as np
import matplotlib.pyplot as plt
import pickle
from sklearn.model_selection import train_test_split
import tqdm
from matplotlib.pyplot import figure
import torch
import torch.nn as nn
import torchvision as tv
%matplotlib inline

## Implementation of own convolution

In [26]:
def my_conv2d(x, kernel, stride=(1,1), padding=(0,0), bias=None):
    """
    Arguments:
    :param  x: input tensor 4d, type tensor.FloatTensor, BxCxHxW,
    :param  kernel: input kernel tensor 3d, type tensor.FloatTensor, CxHxW,
    :param  stride: tuple - stride parameters, set in HxW format,
    :param  padding:  tuple - padding parameters, set in HxW format,
    :param  bias : the input tensor bias is added to the output tensor,
    
    where:
    B is the batch or the number of input,
    C is the number of image channels,
    H is the height of image,
    W is is the width of the image.
    """
    
    # getting input parameters
    in_s = x.size()
    if x.dim() == 3:
        b_in, c_in, h_in, w_in = 1, in_s[0], in_s[1], in_s[2]
    elif x.dim() == 4:
        b_in, c_in, h_in, w_in = in_s[0], in_s[1], in_s[2], in_s[3]
    else:
        raise Exception("ERROR: Wrong input tensor. Input tensor must be 3d or 4d.")
        
    k_s = kernel.size()
    k_c, k_h, k_w = k_s[0], k_s[1], k_s[2]
    
    # output size calculation
    h_out = (h_in + 2 * padding[0] - k_h) / stride[0] + 1
    w_out = (w_in + 2 * padding[1] - k_w) / stride[1] + 1
    
    if not h_out.is_integer() or not w_out.is_integer():
        print("Wrong output dimension. H_out = {}, W_out = {}.".format(h_out, w_out))
        print("Some input units will be left out.")
        h_out = (h_in + 2 * padding[0] - k_h) // stride[0] + 1
        w_out = (w_in + 2 * padding[1] - k_w) // stride[1] + 1
    h_out = int(h_out)
    w_out = int(w_out)
    print("Output size: H_out = {}, W_out = {}".format(h_out, w_out))
        
    # adding padding
    x = torch.from_numpy(np.pad(x.numpy(),
                                ((0, 0), (padding[0],padding[0]), (padding[1],padding[1])),
                                mode='constant'))
    
    # output tensor
    x_out = torch.zeros(h_out, w_out)
    
    # TODO: SMTH WRONG WITH STRIDE. DON'T KNOW...
    # iterating over input tensor
    #for b in range(b_in):
    for c in range(c_in):
        #for h in range(0, h_in + 2 * padding[0] - k_h + 1, stride[0]):
        for h in range(h_out):
            #for w in range(0, w_in + 2 * padding[1] - k_w + 1, stride[1]):
            for w in range(w_out):
                res = 0
                for kc in range(k_c):
                    for kh in range(k_h):
                        for kw in range(k_w):
                            #res += x[c][h + kh][w + kw] * kernel[kc][kh][kw]
                            px += x[c][h * stride[0] + kh][w * stride[1] + kw] * kernel[kc][kh][kw]
                #x_out[int(h/stride[0])][int(w/stride[1])] += (res / k_c)
                x_out[h][w] += (px / k_c)
                            
    return x_out

## Batch normalization module

In [40]:
class BatchNorm2d(nn.Module):
    
    def __init__(self, in_channels, affine=True, beta=0.9, epsilon=1e-8):
        """       
         BatchNorm Initialization
         If the affine flag is set, then gamma and b matrices must be initialized
         to implement affine transformations in the process of training and testing.
         The parameters to be learned are set as a tensor of the corresponding dimension and save their
         self.weight
         self.bias
         
        : param in_channels: the number of input channels of the previous layer
        : param affine: whether to make affine transformation in the learning process
        : param beta: smoothing parameter (momentum)
        : param epsilon: parameter excluding division by zero
        """
        super().__init__()
        
        self.in_c = in_channels
        self.momentum = beta
        self.eps = epsilon
        
        if affine:
            self.gamma = torch.Tensor(1, self.in_c, 1, 1).uniform_()
            self.b = torch.Tensor(1, self.in_c, 1, 1).fill_(0)
        else:
            self.gamma = torch.Tensor(1, self.in_c, 1, 1).fill_(1)
            self.b = torch.Tensor(1, self.in_c, 1, 1).fill_(0)
        
        self.runing_mean = torch.Tensor(self.in_c).fill_(0)
        self.runing_var = torch.Tensor(self.in_c).fill_(1)
        
        
    def forward(self, x):
        """
        Считаем параметры нормализации в режиме обучения, и нормализуем x в обоих режимах
        используем для расчета параметры gamma и b КАК обучаемые, т.е. учитываем, 
        что эти параметры должны быть обучены в процессе тренировки. 
        We consider the normalization parameters in the learning mode, and normalize x in both modes,
        use the gamma and b parameters for the calculation as the trainees,
        i.e. we take into account that these parameters must be trained in the process of training.
        """
        
        if self.training:
            mean = x.contiguous().view(x.size(1), -1).mean(-1)
            var = x.contiguous().view(x.size(1), -1).var(-1)

            self.runing_mean = self.momentum * self.runing_mean + (1.0 - self.momentum) * mean
            self.runing_var = self.momentum * self.runing_var + (1.0 - self.momentum) * var
        else :
            mean = self.runing_mean
            var = self.runing_var
        
        t_mean = torch.t(mean.unsqueeze(0)).unsqueeze(0).unsqueeze(-1).expand_as(x)
        t_var = torch.t(var.unsqueeze(0)).unsqueeze(0).unsqueeze(-1).expand_as(x)
        
        x_hat = self.gamma * (x - t_mean) / np.sqrt(t_var + self.eps) + self.b
            
        return x_hat


In [95]:
import torch

t = torch.tensor([[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
],[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
],[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,18]
]
], dtype=torch.float32)

print(torch.mean(t))
print(t)
m = t.contiguous().view(t.size(0), -1).mean(-1)
print(m.unsqueeze(0).size())
m = torch.t(m.unsqueeze(0)).unsqueeze(0).unsqueeze(-1).expand_as(t.unsqueeze(0))
print(m.size())
print(m)
#m = m.unsqueeze(0)
#print(m.size())
#print(m)
#m = m.unsqueeze(-1)
#print(m.size())
#print(m)
#print(m.expand_as(t.unsqueeze(0)))
#print(t.view(t.size(0), -1))
#print(t.squeeze(2))
#print(torch.mean(t.squeeze()))
#print(torch.mean(t[2]))
print("END")

filter_kernel = torch.FloatTensor(3,4,4).fill_(0)
filter_kernel[1,:,:] = 1

print(t)
#print(t.size())
#print(t.numel())

filter_kernel = torch.FloatTensor(1,3,3).fill_(1)
#filter_kernel[:,1,1] = 8

print(filter_kernel)

my_conv2d(t, filter_kernel, stride=(2,2), padding=(2,2))

tensor(8.5417)
tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.]],

        [[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.]],

        [[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 18.]]])
torch.Size([1, 3])
torch.Size([1, 3, 4, 4])
tensor([[[[8.5000, 8.5000, 8.5000, 8.5000],
          [8.5000, 8.5000, 8.5000, 8.5000],
          [8.5000, 8.5000, 8.5000, 8.5000],
          [8.5000, 8.5000, 8.5000, 8.5000]],

         [[8.5000, 8.5000, 8.5000, 8.5000],
          [8.5000, 8.5000, 8.5000, 8.5000],
          [8.5000, 8.5000, 8.5000, 8.5000],
          [8.5000, 8.5000, 8.5000, 8.5000]],

         [[8.6250, 8.6250, 8.6250, 8.6250],
          [8.6250, 8.6250, 8.6250, 8.6250],
          [8.6250, 8.6250, 8.6250, 8.6250],
          [8.6250, 8.6250, 8.6250, 8.6250]]]])
END
tensor([[[ 1.,  2.,  3.,

tensor([[  3.,  18.,  21.],
        [ 45., 162., 135.],
        [ 66., 216., 164.]])